const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = [
  "./src/Routes/AuthRoute.js",
  "./src/Routes/ClientRoute.js",
  "./src/Routes/DefaultRoute.js",
];

const doc = {
  info: {
    version: "1.0.0",
    title: "Client CRUD",
    description:
      "A Basic CRUD for Clients. Documentation automatically generated by the <b>swagger.autogen</b> module.",
  },
  host: "localhost:8080",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [],
  securityDefinitions: {
    "JWT": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
  },
};

// Just Create doc file
// swaggerAutogen(outputFile, endpointsFiles);

// Create and server up
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./server.js");
});
